---
title: "Homework 4"
author: "Wayne Monical wem2121"
date: "2024-10-27"
output: html_document
---


```{r, message = FALSE}
library(tidyverse)
library(p8105.datasets)
library(plotly)
```



```{r}
rest_inspec = 
  p8105.datasets::rest_inspec |> 
  drop_na(grade, score) |> 
  filter(grade %in% c('A', 'B', 'C')) |> 
  mutate(
    year_month = str_sub(inspection_date, 0, 7),
    year = year(inspection_date),
    month = year(inspection_date))
```



```{r}
rest_inspec$grade |> unique()
```

```{r}
rest_inspec$action |> unique()
```





```{r}
rest_inspec |> 
  filter(boro != 'Missing') |> 
  plot_ly(y =  ~score, type = 'box', x = ~boro, color = ~boro)
```


```{r}
head(rest_inspec)
```


```{r}
rest_inspec |> 
  count(grade) |> 
  plot_ly(x = ~grade, y = ~n, color = ~grade, type = "bar")
```


```{r}
rest_inspec |>
  group_by(year_month) |> 
  count(grade) |> 
  plot_ly(x = ~year_month, y = ~n, color = ~grade, type = 'scatter', mode = 'markers')
```





```{r}
head(rest_inspec)
```

