---
title: "NYC Restaurant Inspection Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Home", href: "index.html", align: left }
      - { title: "Homework 4 Dashboard", href: "rest_inspec_dashboard.html", align: right }
      - { title: "Homework 4 Code", href: "p8105_hw4_wem2121.html", align: right }
      - { title: 'Email' , href: "mailto:w3monical@gmail.com", align: right }
      - { title: 'GitHub', href: "http://github.com/wayne-monical/", align: right }
    theme: cerulean
    
---


```{r}
# rendering this document in r studio: 
# rmarkdown::render("rest_inspec_dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")

# {text: "Homework 4 Dashboard", href: "rest_inspec_dashboard.html", align: right }
#- { text: "Homework 4 Code", href: "p8105_hw4_wem2121.html", align: right }
#      - { icon: "fa-envelope fa-lg", href: "mailto:w3monical@gmail.com", align: right }
#      - { icon: "fa-github fa-lg", href: "http://github.com/wayne-monical/", align: right }

```


```{r setup, include=FALSE}
library(flexdashboard)
library(p8105.datasets)
library(plotly)
library(tidyverse)
```



```{r}
rest_inspec = 
  p8105.datasets::rest_inspec |> 
  mutate(
    year_month = str_sub(inspection_date, 0, 7),
    year = year(inspection_date),
    month = year(inspection_date),
    closed_flag = action %in% c(
      "Establishment Closed by DOHMH.  Violations were cited in the following area(s) and those requiring immediate action were addressed.",
      "Establishment re-closed by DOHMH")
    )
```



Column {data-width=650}
-----------------------------------------------------------------------


### Inspection Grades over Time

```{r}
rest_inspec |>
  drop_na(grade, score) |> 
  filter(grade %in% c('A', 'B', 'C')) |> 
  group_by(year_month) |> 
  count(grade) |> 
  plot_ly(x = ~year_month, y = ~n, color = ~grade, type = 'scatter', mode = 'line')|> 
  layout(xaxis = list(title = 'Time'),
         yaxis = list(title = 'Number of Grades Issued'))
```


Column {data-width=350}
-----------------------------------------------------------------------

### Inspection Scores by Grade 

```{r}
rest_inspec |> 
  drop_na(score) |> 
  filter(grade %in% c('A', 'B', 'C')) |> 
  group_by(grade)|> 
  plot_ly(x = ~grade, color = ~grade, y = ~score, type = 'box' )|> 
  layout(xaxis = list(title = 'Grade'),
         yaxis = list(title = 'Score'))
```


### Proportion of Inspections Resulting in Restaurant Closure by Borough

```{r}
rest_inspec |> 
  filter(boro != 'Missing') |> 
  group_by(boro) |> 
  summarize(perc_closed = mean(closed_flag)) |> 
  plot_ly(x = ~boro, y = ~perc_closed, color = ~boro, type = "bar") |> 
  layout(xaxis = list(title = 'Borough'),
         yaxis = list(title = 'Proportion'))
```